# Generated by Django 4.2.1 on 2023-05-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
